sudo: required

services: 
  - docker

before_install:
  - docker build -t abdelrahman1993/front -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abdelrahman1993/front npm run test -- --coverage

after_success:
    - docker build -t abdelrahman1993/multi-client ./client
    - docker build -t abdelrahman1993/multi-nginx ./nginx
    - docker build -t abdelrahman1993/multi-server ./server
    - docker build -t abdelrahman1993/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push abdelrahman1993/multi-client
    - docker push abdelrahman1993/multi-nginx
    - docker push abdelrahman1993/multi-server
    - docker push abdelrahman1993/multi-worker



# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-2'
#   app: 'docker-react'
#   env: 'DockerReact-env'
#   bucket_name: 'elasticbeanstalk-us-east-2-571580277330'
#   bucket_path: 'docker-react'
#   on:
#     branch: master
  
#   access_key_id: '$AWS_ACCESS_KEY'
#   secret_access_key: '$AWS_SECRET_KEY'