version: "3"
services: 
    mysql:
        image: mysql:latest
        restart: always
        env_file: database.env
            
           
        
    redis:
        image: redis:latest 

    apiserver:
        restart: always
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./server:/app
        env_file: database.env
        depends_on:
            - redis
            - mysql

    worker:
        build: 
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./worker:/app
        env_file: database.env

        depends_on:
            - redis
            - mysql

    client:
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./client:/app
        env_file: database.env

        depends_on:
            - apiserver

    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        restart: always

        ports: 
            - 80:80

        depends_on:
            - apiserver
            - client
            - redis
            - mysql