version: "3"
services: 
    postgres:
        image: postgres:latest
        env_file: database.env
    
    redis:
        image: redis:latest 

    apiserver:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./server:/app
        env_file: database.env

    worker:
        build: 
            context: ./worker
            dockerfile: Dockerfile.env
        volumes: 
            - /app/node_modules
            - ./server:/app
        env_file: database.env

    client:
        build: 
            context: ./client
            dockerfile: Dockerfile.env
        volumes: 
            - /app/node_modules
            - ./client:/app
        env_file: database.env